all:

#  sf_image_uploader:
#    routes_register: true
#    types:
#      offer:
#        object_model: Offer
#        image_model: OfferImage

  thumbnail:
    types:
      uploaded_preview:
        mimetype: image/jpeg
        macro:
          Replica_Macro_ThumbnailFixed: [90, 90, center, center]