all:

#  sf_image_uploader:
#    routes_register: true
#    types:
#      offer:
#        object_model: Offer
#        image_model: OfferImage
#        images_relation: Images

  thumbnail:
    types:
      uploaded_preview:
        mimetype: image/jpeg
        macro:
          Replica_Macro_ThumbnailFixed: [90, 90, center, center]
      preview_for_title:
        mimetype: image/jpeg
        quality: 80
        macro:
          Replica_Macro_ThumbnailFixed: [120, 80]