Image:
  actAs:
    Timestampable: ~
    exSortable: ~
  columns:
    title:     { type: string(255) }
    object_id: { type: integer,     notnull: true }
    size:      { type: integer(8),  notnull: true }
    type:      { type: string(16),  notnull: true }
    path:      { type: string(255) }
  options:
    symfony:
      filter: false
